<?php
// DEV-ONLY (C7). One-time extractor: parses the static infrastructure view
// (R1a state) + the .bg-N rules of css/infrastructure.css and generates
// database/seed-data/facilities.php (hero + 15 facilities, byte-faithful).
// Usage: php database/extract-infrastructure.php

if (PHP_SAPI !== 'cli') {
    exit("CLI only\n");
}

$root = dirname(__DIR__);
$raw  = preg_replace('/<\?php.*?\?>/s', '', file_get_contents("$root/views/pages/infrastructure.php"));
$webroot = is_dir("$root/public_html") ? "$root/public_html" : "$root/html";
$css  = file_get_contents("$webroot/css/infrastructure.css");

function inner_html(DOMNode $n): string
{
    $out = '';
    foreach ($n->childNodes as $c) {
        $out .= $n->ownerDocument->saveHTML($c);
    }
    return $out;
}

// bg image per .bg-N from the css
$bgs = [];
preg_match_all('/\.bg-(\d+)\s*\{[^}]*url\("\.\.\/photos\/([^"]+)"\)/s', $css, $m, PREG_SET_ORDER);
foreach ($m as $hit) {
    $bgs[(int)$hit[1]] = $hit[2];
}

$doc = new DOMDocument();
libxml_use_internal_errors(true);
$doc->loadHTML('<?xml encoding="utf-8"?><div id="__root">' . $raw . '</div>');
libxml_clear_errors();
$xp = new DOMXPath($doc);

// hero slides
$hero = [];
foreach ($xp->query('//div[@id="infraHeroCarousel"]//div[contains(@class,"carousel-item")]') as $item) {
    $img = $xp->query('.//img', $item)->item(0);
    $h5  = $xp->query('.//h5', $item)->item(0);
    $p   = $xp->query('.//p', $item)->item(0);
    $hero[] = [basename($img->getAttribute('src')), $h5 ? trim($h5->textContent) : '', $p ? trim($p->textContent) : ''];
}

// facilities: slice the SOURCE on <section id="bg-N"> boundaries and parse each
// slice with targeted regex — the shipped markup has unclosed divs (e.g. bg-4's
// text div), which DOM repair "fixes" by swallowing the next section's content.
$facilities = [];
preg_match_all('/<section id="bg-(\d+)"/', $raw, $marks, PREG_OFFSET_CAPTURE);
foreach ($marks[1] as $k => [$num, $numOff]) {
    $n     = (int)$num;
    $start = $marks[0][$k][1];
    $end   = isset($marks[0][$k + 1]) ? $marks[0][$k + 1][1] : strlen($raw);
    $slice = substr($raw, $start, $end - $start);

    preg_match('/<h4[^>]*>(.*?)<\/h4>/s', $slice, $hm);
    $name = trim(html_entity_decode(strip_tags($hm[1] ?? "Facility $n"), ENT_QUOTES, 'UTF-8'));

    $paras = [];
    // paragraphs AFTER the text-div opener only (the carousel has no <p>)
    $textPos = strpos($slice, 'infra-new-text');
    if ($textPos !== false) {
        preg_match_all('/<p>(.*?)<\/p>/s', substr($slice, $textPos), $pm);
        foreach ($pm[1] as $inner) {
            $paras[] = '<p>' . $inner . '</p>';
        }
    }

    preg_match_all('/<img[^>]+src="([^"]+)"/', $slice, $im);
    $slides = [];
    foreach ($im[1] as $src) {
        $slides[] = basename($src);
    }

    $facilities[$n] = [
        'name'             => $name,
        'description_html' => implode("\n    ", $paras),
        'bg_image'         => $bgs[$n] ?? null,
        'carousel'         => $slides,
    ];
}
ksort($facilities);

// nav labels (order sanity check — should match facility names)
$nav = [];
foreach ($xp->query('//div[contains(@class,"btn-group")]//label') as $lbl) {
    $nav[] = trim($lbl->textContent);
}

@mkdir("$root/database/seed-data", 0775, true);
file_put_contents(
    "$root/database/seed-data/facilities.php",
    "<?php\n// GENERATED by database/extract-infrastructure.php (C7) from the static R1a\n// view + css/infrastructure.css .bg-N rules. Byte-faithful shipped content.\nreturn " . var_export(['hero' => $hero, 'facilities' => array_values($facilities), 'nav' => $nav], true) . ";\n"
);
fwrite(STDERR, sprintf("hero=%d facilities=%d nav=%d bgs=%d\n", count($hero), count($facilities), count($nav), count($bgs)));
foreach (array_values($facilities) as $i => $f) {
    $navName = $nav[$i] ?? '?';
    if (trim($navName) !== trim($f['name'])) {
        fwrite(STDERR, "  NOTE nav[$i]='{$navName}' vs section name='{$f['name']}'\n");
    }
}
echo "written: database/seed-data/facilities.php\n";
