<?php
// DEV-ONLY (C8). One-time extractor: parses the static achievements view (R1a
// state) and generates database/seed-data/achievements.php (hero + the
// 'achievement' and 'award' item lists, byte-faithful, in page order).
// Usage: php database/extract-achievements.php

if (PHP_SAPI !== 'cli') {
    exit("CLI only\n");
}

$root = dirname(__DIR__);
$raw  = preg_replace('/<\?php.*?\?>/s', '', file_get_contents("$root/views/pages/achievements.php"));

// hero slides
$hero = [];
preg_match('/<section class="abt-carousel.*?<\/section>/s', $raw, $hm);
preg_match_all('/<div class="carousel-item[^"]*">(.*?)<\/div>\s*<\/div>/s', $hm[0] ?? '', $items, PREG_SET_ORDER);
foreach ($items as $it) {
    preg_match('/<img[^>]+src="[^"]*photos\/([^"]+)"/', $it[1], $im);
    preg_match('/<h5[^>]*>(.*?)<\/h5>/s', $it[1], $hm5);
    preg_match('/<p[^>]*>(.*?)<\/p>/s', $it[1], $pm);
    $hero[] = [
        basename($im[1] ?? ''),
        trim(html_entity_decode(strip_tags($hm5[1] ?? ''), ENT_QUOTES, 'UTF-8')),
        trim(html_entity_decode(strip_tags($pm[1] ?? ''), ENT_QUOTES, 'UTF-8')),
    ];
}

// the two typed lists: items before the "Awards given by" heading are
// achievements; after it, awards. Slice on the second .home-text block.
$split = strpos($raw, 'Awards given by');
$parts = ['achievement' => substr($raw, 0, $split), 'award' => substr($raw, $split)];
$rows = [];
foreach ($parts as $type => $chunk) {
    preg_match_all('/<div class="item(?: reverse)?">(.*?)<\/div>\s*(?=<div class="item|<\/div>)/s', $chunk, $im, PREG_SET_ORDER);
    foreach ($im as $one) {
        $inner = $one[1];
        preg_match('/<img[^>]+src="[^"]*photos\/(?!trophy)([^"]+)"/', $inner, $img);
        preg_match('/<h3[^>]*>(.*?)<\/h3>/s', $inner, $h3);
        preg_match('/<p[^>]*>(.*?)<\/p>/s', $inner, $p);
        if (!isset($h3[1])) {
            continue;
        }
        $rows[] = [
            'type'    => $type,
            'title'   => trim(html_entity_decode(strip_tags($h3[1]), ENT_QUOTES, 'UTF-8')),
            'subtext' => trim(html_entity_decode(strip_tags($p[1] ?? ''), ENT_QUOTES, 'UTF-8')),
            'image'   => basename($img[1] ?? ''),
        ];
    }
}

@mkdir("$root/database/seed-data", 0775, true);
file_put_contents(
    "$root/database/seed-data/achievements.php",
    "<?php\n// GENERATED by database/extract-achievements.php (C8) from the static R1a view.\nreturn " . var_export(['hero' => $hero, 'rows' => $rows], true) . ";\n"
);
$a = count(array_filter($rows, fn ($r) => $r['type'] === 'achievement'));
$w = count(array_filter($rows, fn ($r) => $r['type'] === 'award'));
fwrite(STDERR, "hero=" . count($hero) . " achievements=$a awards=$w\n");
foreach ($rows as $r) {
    if ($r['image'] === '') {
        fwrite(STDERR, "  NOTE missing image for: {$r['title']}\n");
    }
}
echo "written: database/seed-data/achievements.php\n";
