<?php
// DEV-ONLY (C6). One-time extractor: parses the static sports view (R1a state)
// and generates database/seed-data/sports.php (hero slides + the 9 sport
// cards, byte-faithful). Usage: php database/extract-sports.php

if (PHP_SAPI !== 'cli') {
    exit("CLI only\n");
}

$root = dirname(__DIR__);
$raw  = preg_replace('/<\?php.*?\?>/s', '', file_get_contents("$root/views/pages/sports.php"));

function inner_html(DOMNode $n): string
{
    $out = '';
    foreach ($n->childNodes as $c) {
        $out .= $n->ownerDocument->saveHTML($c);
    }
    return $out;
}

$doc = new DOMDocument();
libxml_use_internal_errors(true);
$doc->loadHTML('<?xml encoding="utf-8"?><div id="__root">' . $raw . '</div>');
libxml_clear_errors();
$xp = new DOMXPath($doc);

$hero = [];
foreach ($xp->query('//section[contains(@class,"abt-carousel")]//div[contains(@class,"carousel-item")]') as $item) {
    $img = $xp->query('.//img', $item)->item(0);
    $h5  = $xp->query('.//h5', $item)->item(0);
    $p   = $xp->query('.//p', $item)->item(0);
    $hero[] = [basename($img->getAttribute('src')), trim($h5->textContent), trim($p->textContent)];
}

$sports = [];
$suffixes = [];
foreach ($xp->query('//section[contains(@class,"sports-card")]') as $sec) {
    // record the reveal-class suffix sequence ('', '2', '3'…)
    preg_match('/sports-card-reveal(\d*)/', $sec->getAttribute('class'), $m);
    $suffixes[] = $m[1] ?? '';
    foreach ($xp->query('.//div[contains(@class,"col-md-4")]', $sec) as $col) {
        $img  = $xp->query('.//img', $col)->item(0);
        $name = $xp->query('.//h3[contains(@class,"card-title")]', $col)->item(0);
        $time = $xp->query('.//p[contains(@class,"card-text")]', $col)->item(0);
        $body = $xp->query('.//div[contains(@class,"collapse")]//div[contains(@class,"card-body")]', $col)->item(0);
        if (!$name) {
            continue;
        }
        $sports[] = [
            'name'          => trim($name->textContent),
            'training_time' => $time ? trim($time->textContent) : '',
            'details_html'  => $body ? trim(inner_html($body)) : '',
            'image'         => $img ? basename($img->getAttribute('src')) : null,
        ];
    }
}

@mkdir("$root/database/seed-data", 0775, true);
file_put_contents(
    "$root/database/seed-data/sports.php",
    "<?php\n// GENERATED by database/extract-sports.php (C6) from the static R1a view.\n// Byte-faithful shipped content — edit via the admin panel, not here.\nreturn " . var_export(['hero' => $hero, 'sports' => $sports, 'suffixes' => $suffixes], true) . ";\n"
);
fwrite(STDERR, sprintf("hero=%d sports=%d suffixes=%s\n", count($hero), count($sports), json_encode($suffixes)));
echo "written: database/seed-data/sports.php\n";
