<?php
// DEV-ONLY (C9). One-time extractor for the gallery family:
//  - per album (10 — gal-sciexpo is a stale orphan copy of gal-spach and
//    becomes a 301): title, years (radio labels, checked default), photos per
//    year IN ORDER (commented-out blocks skipped), plus the album's verbatim
//    <style> block written to public_html/css/albums/{slug}.css;
//  - the hub's album cards (image/title/order) from views/pages/gallery.php.
// Usage: php database/extract-gallery.php

if (PHP_SAPI !== 'cli') {
    exit("CLI only\n");
}

$root    = dirname(__DIR__);
$webroot = is_dir("$root/public_html") ? "$root/public_html" : "$root/html";
$slugs   = ['gal-annual', 'gal-sports', 'gal-independence', 'gal-children', 'gal-teacher',
            'gal-expressionz', 'gal-expo', 'gal-grad', 'gal-alumni', 'gal-spach'];

@mkdir("$webroot/css/albums", 0775, true);

$albums = [];
foreach ($slugs as $slug) {
    $raw = preg_replace('/<\?php.*?\?>/s', '', file_get_contents("$root/views/pages/$slug.php"));
    $raw = preg_replace('/<!--.*?-->/s', '', $raw); // drop commented-out year blocks etc.

    // verbatim style → css file
    preg_match('/<style>(.*?)<\/style>/s', $raw, $sm);
    file_put_contents("$webroot/css/albums/$slug.css", trim($sm[1] ?? '') . "\n");

    preg_match('/<h1>(.*?)<\/h1>/s', $raw, $hm);
    $title = trim(html_entity_decode($hm[1] ?? $slug, ENT_QUOTES, 'UTF-8'));

    // years from the radio inputs (order + checked)
    $years = [];
    preg_match_all('/<input[^>]+id="btnradio([^"]+)"([^>]*)>/', $raw, $rm, PREG_SET_ORDER);
    foreach ($rm as $r) {
        $years[] = ['label' => $r[1], 'checked' => str_contains($r[2], 'checked')];
    }

    // photos per year, in document order
    $photos = [];
    preg_match_all('/<div class="image year-([^"]+)">\s*<img[^>]+src="[^"]*photos\/([^"]+)"/', $raw, $pm, PREG_SET_ORDER);
    foreach ($pm as $p) {
        $photos[$p[1]][] = basename($p[2]);
    }

    $albums[$slug] = ['title' => $title, 'years' => $years, 'photos' => $photos];
    fwrite(STDERR, sprintf(
        "%-18s title='%s' years=%s photos=%s\n",
        $slug, $title,
        json_encode(array_column($years, 'label')),
        json_encode(array_map('count', $photos))
    ));
}

// hub cards: image + title per album link, in page order
$hub = preg_replace('/<\?php.*?\?>/s', '', file_get_contents("$root/views/pages/gallery.php"));
$cards = [];
preg_match_all('/<img[^>]+src="[^"]*photos\/([^"]+)"[^>]*>\s*<div class="card-body">\s*<h3[^>]*>(.*?)<\/h3>\s*<p class="card-text">(.*?)<\/p>\s*<a href="\/(gal-[a-z]+)\.php"/s', $hub, $cm, PREG_SET_ORDER);
foreach ($cm as $c) {
    $cards[$c[4]] = [
        'card_image' => basename($c[1]),
        'card_title' => trim(html_entity_decode(strip_tags($c[2]), ENT_QUOTES, 'UTF-8')),
        'card_sub'   => trim(html_entity_decode(strip_tags($c[3]), ENT_QUOTES, 'UTF-8')),
    ];
}
fwrite(STDERR, 'hub cards: ' . json_encode(array_keys($cards)) . "\n");
$order = array_keys($cards);
foreach ($albums as $slug => &$A) {
    $A['card_image'] = $cards[$slug]['card_image'] ?? null;
    $A['card_title'] = $cards[$slug]['card_title'] ?? $A['title'];
    $A['card_sub']   = $cards[$slug]['card_sub'] ?? '';
    $A['hub_pos']    = array_search($slug, $order, true);
}

@mkdir("$root/database/seed-data", 0775, true);
file_put_contents(
    "$root/database/seed-data/gallery.php",
    "<?php\n// GENERATED by database/extract-gallery.php (C9) from the static R1c views.\nreturn " . var_export($albums, true) . ";\n"
);
echo "written: database/seed-data/gallery.php + css/albums/*.css\n";
