<?php
// GENERATED by database/extract-academies.php (C5) from the static R1b views
// + the co-curriculum grid. Byte-faithful except the six .jpg->.jpeg bug-1/2
// fixes. Edit via the admin panel, not here.
return array (
  'tamilacademy' => 
  array (
    'banner_title' => 'Valanar Ilakkiya Mandram',
    'banner_subtitle' => 'Tamil Academy',
    'content_heading' => 'Tamil Academy',
    'body_html' => '<p> In our school every academic year in the month of June we have the inauguration of various Academies like <span style="color:#ffd700;font-size:25px;font-weight:bolder;">Valanar Ilakkiya Mandram </span>,  which will be celebrated in a grand manner.A special guest will be
        invited and programme will be conducted.During these days, are students showcase their talents through dance, drama, mime,mono act, oration etc., through these  our students  developing their
        communicative skills, innovation ,time management, logical thinking ,leadership, understanding the learning process and goals, build confidence and broder perspectives. Similarly in the month of February validity function will be celebrated.
    </p>
    <p>Every Friday\'s for the classes 6, 7 and 8 subject
        wise Academy  will be conducted from 8.30 - 9 am.</p>',
    'bg_image' => 'tamaca1.jpg',
    'carousel' => 
    array (
      0 => 'tamaca2.jpg',
      1 => 'tamaca3.jpg',
      2 => 'tamaca4.jpg',
    ),
    'card_title' => 'Academy of Tamil',
    'card_subtitle' => 'Valanar Ilakkiya Mandram',
    'card_image' => 'tamaca1.jpg',
  ),
  'englishacademy' => 
  array (
    'banner_title' => 'Excel English Academy',
    'banner_subtitle' => 'English Academy',
    'content_heading' => 'English Academy',
    'body_html' => '<p> In our school every academic year in the month of June we have the inauguration of various Academies like <span style="color:#ffd700;font-size:25px;font-weight:bolder;">Excel English Academy </span>,  which will be celebrated in a grand manner.A special guest will be
        invited and programme will be conducted.During these days, are students showcase their talents through dance, drama, mime,mono act, oration etc., through these  our students  developing their
        communicative skills, innovation ,time management, logical thinking ,leadership, understanding the learning process and goals, build confidence and broder perspectives. Similarly in the month of February validity function will be celebrated.
    </p>
    <p>Every Friday\'s for the classes 6, 7 and 8 subject
        wise Academy  will be conducted from 8.30 - 9 am.</p>',
    'bg_image' => 'engaca2.jpg',
    'carousel' => 
    array (
      0 => 'engaca3.jpg',
      1 => 'engaca4.jpg',
      2 => 'engaca1.jpg',
    ),
    'card_title' => 'Academy of English',
    'card_subtitle' => 'Excel English Academy',
    'card_image' => 'engaca2.jpg',
  ),
  'mathsacademy' => 
  array (
    'banner_title' => 'Math Magician Academy',
    'banner_subtitle' => 'Mathematics Academy',
    'content_heading' => 'Mathematics Academy',
    'body_html' => '<p> In our school every academic year in the month of June we have the inauguration of various Academies like <span style="color:#ffd700;font-size:25px;font-weight:bolder;">Math Magician Academy </span>,  which will be celebrated in a grand manner.A special guest will be
        invited and programme will be conducted.During these days, are students showcase their talents through dance, drama, mime,mono act, oration etc., through these  our students  developing their
        communicative skills, innovation ,time management, logical thinking ,leadership, understanding the learning process and goals, build confidence and broder perspectives. Similarly in the month of February validity function will be celebrated.
    </p>
    <p>Every Friday\'s for the classes 6, 7 and 8 subject
        wise Academy  will be conducted from 8.30 - 9 am.</p>',
    'bg_image' => 'mataca1.jpg',
    'carousel' => 
    array (
      0 => 'mataca2.jpg',
      1 => 'mataca3.jpg',
      2 => 'mataca4.jpg',
    ),
    'card_title' => 'Academy of Maths',
    'card_subtitle' => 'Math Magician Academy',
    'card_image' => 'mataca1.jpg',
  ),
  'scienceacademy' => 
  array (
    'banner_title' => 'Masterminds Academy',
    'banner_subtitle' => 'Science Academy',
    'content_heading' => 'Science Academy',
    'body_html' => '<p> In our school every academic year in the month of June we have the inauguration of various Academies like <span style="color:#ffd700;font-size:25px;font-weight:bolder;">Masterminds Academy </span>,  which will be celebrated in a grand manner.A special guest will be
        invited and programme will be conducted.During these days, are students showcase their talents through dance, drama, mime,mono act, oration etc., through these  our students  developing their
        communicative skills, innovation ,time management, logical thinking ,leadership, understanding the learning process and goals, build confidence and broder perspectives. Similarly in the month of February validity function will be celebrated.
    </p>
    <p>Every Friday\'s for the classes 6, 7 and 8 subject
        wise Academy  will be conducted from 8.30 - 9 am.</p>',
    'bg_image' => 'sciaca1.jpg',
    'carousel' => 
    array (
      0 => 'sciaca2.jpg',
      1 => 'sciaca3.jpg',
      2 => 'sciaca4.jpg',
    ),
    'card_title' => 'Academy of Science',
    'card_subtitle' => 'Masterminds Academy',
    'card_image' => 'sciaca1.jpg',
  ),
  'socialacademy' => 
  array (
    'banner_title' => 'Patriotic Panthers Academy',
    'banner_subtitle' => 'Social Academy',
    'content_heading' => 'Social Academy',
    'body_html' => '<p> In our school every academic year in the month of June we have the inauguration of various Academies like <span style="color:#ffd700;font-size:25px;font-weight:bolder;">Patriotic Panthers Academy </span>,  which will be celebrated in a grand manner.A special guest will be
        invited and programme will be conducted.During these days, are students showcase their talents through dance, drama, mime,mono act, oration etc., through these  our students  developing their
        communicative skills, innovation ,time management, logical thinking ,leadership, understanding the learning process and goals, build confidence and broder perspectives. Similarly in the month of February validity function will be celebrated.
    </p>
    <p>Every Friday\'s for the classes 6, 7 and 8 subject
        wise Academy  will be conducted from 8.30 - 9 am.</p>',
    'bg_image' => 'sstaca1.jpg',
    'carousel' => 
    array (
      0 => 'sstaca2.jpg',
      1 => 'sstaca3.jpg',
      2 => 'sstaca4.jpg',
    ),
    'card_title' => 'Academy of Social Science',
    'card_subtitle' => 'Patriotic Panthers Academy',
    'card_image' => 'sstaca1.jpg',
  ),
  'langacademy' => 
  array (
    'banner_title' => 'Academy of Foreign Languages',
    'banner_subtitle' => 'Spanish - German - French',
    'content_heading' => 'Academy of Foreign Languages',
    'body_html' => '<p>Focusing foreign language
     Understanding the Global needs of foreign languages, we inculcated foreign languages and transforming power to students.
     <span style="color:#ffd700;font-size:25px;font-weight:bolder;">French, Spanish and German languages</span> are Designed for 6,7,and 8th grades .
     it is to thrive to enhances the cognitive developments. We aim to foster a
     love for languages and Our Mentors employ innovative techniques to ensure
     every students to gain proficiency and confidence in their chosen language.Thus
     St Joseph\'s ward/Students are focused in holistic growth for their bright future.</p>',
    'bg_image' => 'langaca1.jpg',
    'carousel' => 
    array (
      0 => 'langaca2.jpg',
      1 => 'langaca3.jpg',
      2 => 'langaca4.jpg',
    ),
    'card_title' => 'Academy of Foreign Languages',
    'card_subtitle' => 'Spanish - German - French',
    'card_image' => 'langaca1.jpg',
  ),
  'instrumentacademy' => 
  array (
    'banner_title' => 'Instrumental Academy',
    'banner_subtitle' => 'Musical Instruments',
    'content_heading' => 'Instrumental Academy',
    'body_html' => '<p> A musical instrument academy is an educational club dedicated to teaching students how to play various <span style="color:#ffd700;font-size:25px;font-weight:bolder;">Musical Instruments</span>.
        These academies cater to a wide range of skill levels, from beginners to intermediate musicians, and offer instruction in an electronic instruments like keyboard and more. A key feature of a musical instrument academy is its staff of qualified instructors. These instructors often have extensive backgrounds
        in music education, performance, and pedagogy, ensuring that students receive high-quality instruction. Academies typically offer a diverse curriculum that includes individual lessons, group classes, music theory, ear training, and performance opportunities. Many academies emphasize the importance of performance
        by organizing recitals, concerts, and other events where students can showcase their talents. Attending an academy provides a structured learning environment, which can be more effective than self-study or informal lessons. With professional instructors, a diverse curriculum, and ample performance opportunities,
        these academies play a crucial role in nurturing the next generation of musicians.
    </p>',
    'bg_image' => 'insaca2.jpg',
    'carousel' => 
    array (
      0 => 'insaca1.jpg',
      1 => 'insaca3.jpg',
      2 => 'insaca2.jpg',
    ),
    'card_title' => 'Instrumental Academy',
    'card_subtitle' => 'Musical Instruments',
    'card_image' => 'insaca1.jpg',
  ),
  'martialacademy' => 
  array (
    'banner_title' => 'Martial Arts Academy',
    'banner_subtitle' => 'Karate',
    'content_heading' => 'Martial Arts Academy',
    'body_html' => '<p> Karate is maritial art which equip the children with
        confidence and self defence skills. This self confidence
        navigate them to tackle the problemsin the world. it strengthens
        the entire body, improves the stamina, builts the coordination and
        trains the character to the integrity. we offer karate classes to the
        5 grade students on every wednesday. In  addition to that Monday to
        wednesday  a special coaching offered for the classes of 1st to 9th grade
          in the evening 3:30 p.m. to 4:30 p.m.
    </p>',
    'bg_image' => 'karaca1.jpg',
    'carousel' => 
    array (
      0 => 'karaca2.jpg',
      1 => 'karaca3.jpg',
      2 => 'karaca4.jpg',
    ),
    'card_title' => 'Academy of Martial Arts',
    'card_subtitle' => 'Karate',
    'card_image' => 'karaca1.jpg',
  ),
  'communicativeacademy' => 
  array (
    'banner_title' => 'Academy of  Communicative english',
    'banner_subtitle' => 'Effective Communication',
    'content_heading' => 'Academy of  Communicative english',
    'body_html' => '<p>

Communicative English focuses on improving the ability to communicate effectively in various real-life situations. Here are some key areas it typically covers: <br>

<span style="color:#ffd700;font-size:25px;font-weight:bolder;">Speaking Skills:</span> Emphasizes fluency, pronunciation, and the ability to engage in conversations, discussions, and presentations.<br>

<span style="color:#ffd700;font-size:25px;font-weight:bolder;">Listening Skills:</span> Involves understanding spoken English in different accents and contexts, such as conversations, lectures, and media.<br>

<span style="color:#ffd700;font-size:25px;font-weight:bolder;">Reading Skills:</span> Focuses on comprehending and interpreting written texts, ranging from articles and reports to fiction and non-fiction.<br>

<span style="color:#ffd700;font-size:25px;font-weight:bolder;">Writing Skills:</span> Covers writing emails, reports, essays, and other forms of written communication with clarity and coherence.<br>

<span style="color:#ffd700;font-size:25px;font-weight:bolder;">Grammar and Vocabulary:</span> Enhances understanding and correct usage of grammar and expands vocabulary relevant to various contexts.<br>

<span style="color:#ffd700;font-size:25px;font-weight:bolder;">Cultural Awareness:</span> Improves understanding of cultural nuances and appropriate language use in different social and professional settings.<br>

<span style="color:#ffd700;font-size:25px;font-weight:bolder;">Body Language and Non-verbal Communication:</span> Teaches the importance of body language, facial expressions, and other non-verbal cues in effective communication.<br>
    </p>',
    'bg_image' => 'comeaca1.jpg',
    'carousel' => 
    array (
      0 => 'comeaca2.jpg',
      1 => 'comeaca3.jpg',
      2 => 'comeaca4.jpg',
    ),
    'card_title' => 'Academy of Communicative English',
    'card_subtitle' => 'Effective Communication',
    'card_image' => 'comeaca1.jpg',
  ),
  'sportsacademy' => 
  array (
    'banner_title' => 'Academy of Athletes and Sports',
    'banner_subtitle' => 'Sports',
    'content_heading' => 'Academy of Athletes and Sports',
    'body_html' => '<p>
     
      St.Joseph’s Physical department is unique platform in creating vibrant sports stars in various categories.  
      different timing schedule is designed for the entire year.
      Badminton, Handball, table tennis, Tennie koit , Volley ball, Throw ball, Kabbadi.
      Sports Champ were trained in the evenings 
      An array of members take practice in terms till 7.30. <br>
      	As Hallmark. out students reached the pinnacle.<br>
      	zonal winners, District State Level winners.<br>
      	One of one student is sponsored by SAI (Sports Authority of India). <br>
      <span style="color:#ffd700;font-size:24px;font-weight:bolder;">I always felt that my greatest asset was not my physical ability , It was my mental ability. – Bruce Jenner.</span> 
    </p>',
    'bg_image' => 'spoaca1.jpg',
    'carousel' => 
    array (
      0 => 'spoaca2.jpg',
      1 => 'spoaca3.jpg',
      2 => 'spoaca4.jpg',
    ),
    'card_title' => 'Academy of Athletes and Sports',
    'card_subtitle' => 'Sports',
    'card_image' => 'spoaca1.jpg',
  ),
  'vocalacademy' => 
  array (
    'banner_title' => 'Vocal Academy',
    'banner_subtitle' => 'Chorus Singing',
    'content_heading' => 'Vocal Academy',
    'body_html' => '<p>

      The students of our vocal academy receive training in the context of musicality and technicality in the field of music. The structure of the lesson
       plans for the vocal academy has been formulated in a way to provide the in-depth understanding of music to all age groups of the academy. Over the
       training sessions the students gain knowledge on the theoretical and technical aspects with <span style="color:#ffd700;font-size:24px;font-weight:bolder;">Practical</span> examples. The vocal academy not only aims at
       uplifting the student in their vocal skills but also aims at developing the student’s
      potential as a performer which gets applied to every other field in the longer run.
      </p>
    <p>
      The academy also provides awareness about international music and also gets
      the students used to various fields of music such as the musical theatre, arts
      and drama. St.Joseph’s Vocal Academy is a standalone academy which has its unique
       framework to train the students of all age groups. The academy not only creates talented musicians but also creates students with unique personality and charisma.
      </p>',
    'bg_image' => 'vocaca1.jpg',
    'carousel' => 
    array (
      0 => 'vocaca2.jpg',
      1 => 'vocaca3.jpg',
      2 => 'vocaca1.jpg',
    ),
    'card_title' => 'Vocal Academy',
    'card_subtitle' => 'Chorus Singing',
    'card_image' => 'vocaca1.jpg',
  ),
  'yogaacademy' => 
  array (
    'banner_title' => 'Academy of Yoga',
    'banner_subtitle' => 'Yoga',
    'content_heading' => 'Academy of Yoga',
    'body_html' => '<p>

      Yoga classes are offered to the students to awake their individual consciousness by the unison of mind and body. Yoga consists of engaging exercises called
      asanas or postures and pranayama which includes breathing exercises.Yoga is an invaluable practice introduced in schools to enhance students’ overall well-being.
      By incorporating yoga into the daily routine, students can experience numerous benefits, including improved concentration, better memory retention, and reduced stress levels.
       The physical postures (asanas) help in developing flexibility, strength, and balance, while the breathing exercises (pranayama) promote relaxation and mental clarity.

    </p>',
    'bg_image' => 'yogaca1.jpg',
    'carousel' => 
    array (
      0 => 'yogaca1.jpg',
      1 => 'yogaaca2.jpg',
      2 => 'yogaaca3.jpg',
    ),
    'card_title' => 'Academy of Yoga',
    'card_subtitle' => 'Yoga',
    'card_image' => 'yogaca1.jpg',
  ),
  'danceacademy' => 
  array (
    'banner_title' => 'Academy of Classical Dance',
    'banner_subtitle' => 'Bharatanatyam',
    'content_heading' => 'Academy of Classical Dance',
    'body_html' => '<p> <span style="color:#ffd700;font-size:25px;font-weight:bolder;">Bharatanatyam Dance Program at Our School</span> <br>

Our school offers a Bharatanatyam dance program, introducing students to this
classical Tamil Nadu dance form. Third-standard students will complete basic
adavus and hasta mudras within a year. Evening classes for other grades cover
advanced adavus with thalam, hasthas, anga abhinayas, and preparation for exams
and Salangai Poojah. This program
enriches our cultural education and supports students\' holistic development.
    </p>',
    'bg_image' => 'danceaca1.jpg',
    'carousel' => 
    array (
      0 => 'danceaca2.jpg',
      1 => 'danceaca3.jpg',
      2 => 'danceaca4.jpg',
    ),
    'card_title' => 'Academy of Classical Dance',
    'card_subtitle' => 'Bharatanatyam',
    'card_image' => 'danceaca1.jpg',
  ),
  'band' => 
  array (
    'banner_title' => 'Band',
    'banner_subtitle' => 'St. Joseph’s Tradition of Excellence',
    'content_heading' => 'Band',
    'body_html' => '<p>
    St. Joseph’s Tradition of Excellence

The St. Joseph’s Band stands as a testament to our   <span style="color:#ffd700;font-size:24px;font-weight:bolder;">School\'s rich musical heritage.</span>
 Comprising talented students from diverse backgrounds and grade levels, the band
  epitomizes teamwork, discipline, and creativity. Their repertoire spans genres and
  styles, showcasing their instrumental proficiency and performance skills. Whether
  at school assemblies, community events, or prestigious competitions, our musicians
  consistently captivate audiences with their energy, enthusiasm, and dedication to
   musical excellence. We proudly celebrate their achievements and eagerly anticipate
   many more inspiring performances.
    </p>
    <p>

      St.Joseph’s Band is rich in Musical Heritage. It embodies the spirit of
      teamwork, discipline and creativity. The musicians impress the audiences
       with energy and enthusiasm in taking part in Assemblies, Interschool
       competitions and excel in Musical Excellence.

    </p>',
    'bg_image' => 'band1.jpg',
    'carousel' => 
    array (
      0 => 'band2.jpeg',
      1 => 'band3.jpg',
      2 => 'band1.jpg',
    ),
    'card_title' => 'Band',
    'card_subtitle' => 'St. Joseph’s Tradition of Excellence',
    'card_image' => 'band1.jpg',
  ),
  'ncc' => 
  array (
    'banner_title' => 'NCC',
    'banner_subtitle' => 'National Cadet Corps',
    'content_heading' => 'NCC',
    'body_html' => '<p>
    The National Cadet Corps(NCC) is a organization in our school that aims to develop character Comradeship,
     Discipline, Leadership Secular Outlook, Spirit of Adventure and Ideals of Selfless Service among young citizens.
      It operates under the Ministry of Defence.raining camp are conducted to impart
      Military training, physical fitness and leadership skills.
    </p>
    <p>
      <span style="color:#ffd700;font-size:24px;font-weight:bolder;">  Community service: </span> Involvement in Social service activities, Blood donations, cleanliness drives and disaster relief. <br>
      <span style="color:#ffd700;font-size:24px;font-weight:bolder;">Competitions: </span>Inter unit, Inter group and National level competitions in drill shooting and cultural activities and events.
    </p>',
    'bg_image' => 'ncc1.jpg',
    'carousel' => 
    array (
      0 => 'ncc2.jpg',
      1 => 'ncc3.jpg',
      2 => 'ncc1.jpg',
    ),
    'card_title' => 'NCC',
    'card_subtitle' => 'National Cadet Corps',
    'card_image' => 'ncc1.jpg',
  ),
  'abacusacademy' => 
  array (
    'banner_title' => 'Academy of Abacus',
    'banner_subtitle' => 'Saibodhi Abacus Academy',
    'content_heading' => 'Academy of Abacus',
    'body_html' => '<p>

      "Unlock your child\'s math potential with Saibodhi Abacus Academy, proudly partnering with St.Joseph Matric HR.Sec School!
   Our expert coaches use fun and interactive methods to teach abacus education, boosting: <br>

   <span style="color:#ffd700;font-size:24px;font-weight:bolder;">- Speed and accuracy. <br>
- Concentration and focus.<br>
- Listening skills and memory.<br>
- Visualization and mental math abilities.<br>
- Left and right brain development.<br> </span>

And, as a bonus, our abacus training also improves physical strength! We proudly teach the abacus the way of Acupuncture, making it a holistic learning experience.

    </p>',
    'bg_image' => 'abacaca1.jpeg',
    'carousel' => 
    array (
      0 => 'abacaca2.jpg',
      1 => 'abacaca3.jpg',
      2 => 'abacaca4.jpeg',
    ),
    'card_title' => 'Academy of Abacus',
    'card_subtitle' => 'Saibodhi Abacus Academy',
    'card_image' => 'abacaca1.jpeg',
  ),
  'artandexpo' => 
  array (
    'banner_title' => 'Art and Crafts Expo',
    'banner_subtitle' => 'Innovation',
    'content_heading' => 'Art and Crafts Expo',
    'body_html' => '<p>

      "Unlock your child\'s creative potential with St.Joseph Matric HR.Sec School!
   Our teachers motivate the students by,boosting: <br>

   <span style="color:#ffd700;font-size:24px;font-weight:bolder;">- Creativeness. <br>
- Community engagement.<br>
- Cultural exchange.<br> </span>

    </p>',
    'bg_image' => 'artexpo0.jpeg',
    'carousel' => 
    array (
      0 => 'artexpo1.jpeg',
      1 => 'artexpo2.jpeg',
      2 => 'artexpo3.jpeg',
    ),
    'card_title' => 'Art and Crafts Expo',
    'card_subtitle' => 'Innovation',
    'card_image' => 'artexpo0.jpeg',
  ),
  'artacademy' => 
  array (
    'banner_title' => 'Academy of Art and Crafts',
    'banner_subtitle' => 'Creative Thinking',
    'content_heading' => 'Academy of Art and Crafts',
    'body_html' => '<p>Art and crafting encompass a wide range of creative activities, from painting and drawing to sculpting, knitting, and more.
        It\'s a wonderful way to  <span style="color:#ffd700;font-size:25px;font-weight:bolder;">express creativity, relax, and create something unique</span>. What specific aspect of art or crafting are students interested in?
        As a milestone Art and craft expo was conducted  every year participating in an art and crafting expo can be a fantastic experience! Students were
        showcasing their creativity and demonstrations.
        It\'s a great opportunity to discover new techniques, get inspired by different styles,</p>',
    'bg_image' => 'artaca1.jpg',
    'carousel' => 
    array (
      0 => 'artaca2.jpg',
      1 => 'artaca3.jpg',
      2 => 'artaca4.jpg',
    ),
    'card_title' => 'Academy of Art and Crafts',
    'card_subtitle' => 'Creative Thinking',
    'card_image' => 'artaca1.jpg',
  ),
);
