<?php
// GENERATED by database/extract-achievements.php (C8) from the static R1a view.
return array (
  'hero' => 
  array (
    0 => 
    array (
      0 => 'achbg.jpg',
      1 => 'Our Achievements',
      2 => 'About our achievements',
    ),
    1 => 
    array (
      0 => 'achoverall.jpg',
      1 => 'Our Achievements',
      2 => 'About our achievements',
    ),
    2 => 
    array (
      0 => 'achcric.jpg',
      1 => 'Our Achievements',
      2 => 'About our achievements',
    ),
  ),
  'rows' => 
  array (
    0 => 
    array (
      'type' => 'achievement',
      'title' => 'Zonal Level Athletics Meet',
      'subtext' => 'Overall Winner - 2023',
      'image' => 'achoverall.jpg',
    ),
    1 => 
    array (
      'type' => 'achievement',
      'title' => 'District Level Athletics Meet',
      'subtext' => 'Venue: Karamadai VidhyaVikash -- Overall Runners - 2023',
      'image' => 'achdist.jpg',
    ),
    2 => 
    array (
      'type' => 'achievement',
      'title' => 'National Level Yoga',
      'subtext' => 'Medal Winners',
      'image' => 'achnatyoga.jpg',
    ),
    3 => 
    array (
      'type' => 'achievement',
      'title' => 'State Level Medal Winners',
      'subtext' => 'Appreciate by Commissioner of Police',
      'image' => 'achstate.jpg',
    ),
    4 => 
    array (
      'type' => 'achievement',
      'title' => 'Selected for SAI Camp',
      'subtext' => 'Banglore - 2024',
      'image' => 'achsai.jpg',
    ),
    5 => 
    array (
      'type' => 'achievement',
      'title' => 'National Level Athletic Meet',
      'subtext' => 'Gujarat - 2024',
      'image' => 'achguj.jpg',
    ),
    6 => 
    array (
      'type' => 'achievement',
      'title' => 'TamilNadu Sports Yoga Competition',
      'subtext' => 'Participated and Won Prizes - 2023',
      'image' => 'achyog.jpg',
    ),
    7 => 
    array (
      'type' => 'achievement',
      'title' => 'Sri Shakthi College Cricket Trophy',
      'subtext' => 'Third Place(3)',
      'image' => 'achcric.jpg',
    ),
    8 => 
    array (
      'type' => 'achievement',
      'title' => 'District Level Winners',
      'subtext' => 'Participated in State 2023',
      'image' => 'achmedal.jpg',
    ),
    9 => 
    array (
      'type' => 'achievement',
      'title' => 'Table Tennis Zonals',
      'subtext' => 'Winners - All Category - 2023',
      'image' => 'achtt.jpg',
    ),
    10 => 
    array (
      'type' => 'award',
      'title' => 'Certificate of Distinction',
      'subtext' => 'For Securing 80% in all Subjects',
      'image' => 'certificate1.jpg',
    ),
    11 => 
    array (
      'type' => 'award',
      'title' => 'Certificate of Merit',
      'subtext' => 'For Securing 60% in all Subjects',
      'image' => 'certificate2.jpg',
    ),
    12 => 
    array (
      'type' => 'award',
      'title' => 'Certificate of Achievement',
      'subtext' => 'For Intramural Winners',
      'image' => 'certificate3.jpg',
    ),
    13 => 
    array (
      'type' => 'award',
      'title' => 'Certificate of Achievement',
      'subtext' => 'For all other Achievements',
      'image' => 'certificate4.jpg',
    ),
  ),
);
