<?php
// GENERATED by database/extract-infrastructure.php (C7) from the static R1a
// view + css/infrastructure.css .bg-N rules. Byte-faithful shipped content.
return array (
  'hero' => 
  array (
    0 => 
    array (
      0 => 's-3.jpg',
      1 => 'Our Infrastructure',
      2 => 'Innovative Learning Spaces',
    ),
    1 => 
    array (
      0 => 'oaud1.jpg',
      1 => 'Our Infrastructure',
      2 => 'Future-Ready Facilities',
    ),
    2 => 
    array (
      0 => 'smclass1.jpg',
      1 => 'Our Infrastructure',
      2 => 'Dynamic Learning Environments',
    ),
  ),
  'facilities' => 
  array (
    0 => 
    array (
      'name' => 'Smart Classrooms',
      'description_html' => '<p>Classrooms equipped with smart boards in our school is a digital tool that offers an interactive learning environment, 
       multimedia  presentations and making education more interactive and effective.</p>',
      'bg_image' => 'smclass2.jpg',
      'carousel' => 
      array (
        0 => 'smclass1.jpg',
        1 => 'smclass2.jpg',
        2 => 'smclass4.jpg',
      ),
    ),
    1 => 
    array (
      'name' => 'Indoor Auditorium',
      'description_html' => '<p>The indoor auditorium is an
    enclosed space designed for assemblies, performances, and events .It facilitates a range of 
    activities in a controlled environment with comfort.</p>',
      'bg_image' => 'aud2.jpg',
      'carousel' => 
      array (
        0 => 'aud1.jpg',
        1 => 'aud3.jpg',
        2 => 'aud4.jpg',
      ),
    ),
    2 => 
    array (
      'name' => 'Outdoor Auditorium',
      'description_html' => '<p>Our school outdoor auditorium provides an open-air space for assemblies and events and offers a 
      versatile venue for students to engage in various activities.</p>',
      'bg_image' => 'oaud1.jpg',
      'carousel' => 
      array (
        0 => 'oaud2.jpg',
        1 => 'oaud3.jpg',
        2 => 'oaud4.jpg',
      ),
    ),
    3 => 
    array (
      'name' => 'Conference Hall',
      'description_html' => '<p>The conference hall in ourschool serves as a multipurpose space for meetings, presentations, and events. It is equipped with 
      audio-visual aids and comfortable seating to facilitate effective communication.</p>',
      'bg_image' => 'conh1.jpeg',
      'carousel' => 
      array (
        0 => 'conh2.jpeg',
        1 => 'conh3.jpeg',
      ),
    ),
    4 => 
    array (
      'name' => 'KG Play Area',
      'description_html' => '<p>The kindergarten play area in our school is a safe space designed for young children to explore, play, and develop 
      essential motor and social skills. It also helps them in learning through play.</p>',
      'bg_image' => 'kgplay1.jpg',
      'carousel' => 
      array (
        0 => 'kgplay2.jpg',
        1 => 'kgplay3.jpg',
        2 => 'kgplay4.jpg',
      ),
    ),
    5 => 
    array (
      'name' => 'Lab Facilities',
      'description_html' => '<p>The lab facility in our school provides students with hands-on learning experiences in subjects like science and Computer science. We have  equipped it with essential tools and safety measures. These labs enable 
      practical experimentation and foster a deeper understanding of theoretical concepts.</p>
    <p>
     <span> Science Laboratory: </span>
    A science lab is a workplace for the conduct of scientific research. It helps students to remember the concepts better and to transfer  the experience to real life situations.
    Our school has the best designed and safe science laboratories.<br>
    <span> Physics Lab:</span>
    Our Physics lab is aimed in enabling students to learn physics theories in a more elaborative manner of its applications.<br>
    <span>Chemistry Lab:</span>
     The chemistry lab is designed with keeping all the statutory norms and safety standards. It is well ventilated as well as spacious.<br>
    <span> Biology Lab:</span>
    In the biology lab, the students study detailed structures, morphological, histological and physiological aspects of plants and animals.<br>

      </p>',
      'bg_image' => 'clab1.jpg',
      'carousel' => 
      array (
        0 => 'clab1.jpg',
        1 => 'clab2.jpg',
        2 => 'clab3.jpg',
        3 => 'lab2.jpg',
        4 => 'lab4.jpg',
      ),
    ),
    6 => 
    array (
      'name' => 'Parking Facility',
      'description_html' => '<p>The parking facility in our school is designed to accommodate vehicles of students, staff, and visitors. It is 
      well-organized, secure, and accessible, ensuring smooth traffic flow and safety.</p>',
      'bg_image' => 'park1.jpg',
      'carousel' => 
      array (
        0 => 'park1.jpg',
        1 => 'park2.jpg',
      ),
    ),
    7 => 
    array (
      'name' => 'Sports Room',
      'description_html' => '<p>
      Sports room in our school is a dedicated space where students can store equipment, change into athletic gear, 
      and prepare for physical activities and team sports. It typically includes lockers, benches, and storage for various sports equipment.

      </p>',
      'bg_image' => 'sproom1.jpg',
      'carousel' => 
      array (
        0 => 'sproom2.jpg',
        1 => 'sproom3.jpg',
      ),
    ),
    8 => 
    array (
      'name' => 'Transport Facility',
      'description_html' => '<p>The school\'s transport facility ensures safe and reliable travel for students, with   well-maintained buses covering various routes.</p>',
      'bg_image' => 'bus1.jpg',
      'carousel' => 
      array (
        0 => 'bus1.jpg',
        1 => 'bus2.jpg',
      ),
    ),
    9 => 
    array (
      'name' => 'Chapel',
      'description_html' => '<p>
      The school campus chapel is a serene space for reflection and spiritual growth, offering a peaceful atmosphere.


      </p>',
      'bg_image' => 'chapel1.jpg',
      'carousel' => 
      array (
        0 => 'chapel1.jpg',
        1 => 'chapel2.jpg',
      ),
    ),
    10 => 
    array (
      'name' => 'E-Library',
      'description_html' => '<p>The e-library in our school provides students with digital access to a wide range of books, journals, and educational resources which also immerses them in a world of technology.</p>',
      'bg_image' => 'elib1.jpg',
      'carousel' => 
      array (
        0 => 'elib1.jpg',
        1 => 'elib2.jpg',
        2 => 'elib3.jpg',
      ),
    ),
    11 => 
    array (
      'name' => 'Knowledge Center',
      'description_html' => '<p>
      The knowledge centre in our school serves as a hub for learning and research. It\'s  equipped with books, computers, and study spaces to support students\' academic pursuits.



      </p>',
      'bg_image' => 'knowcent2.jpg',
      'carousel' => 
      array (
        0 => 'knowcent1.jpg',
        1 => 'knowcent2.jpg',
      ),
    ),
    12 => 
    array (
      'name' => 'Food Court',
      'description_html' => '<p>The food court in our school offers a variety of nutritious meal options promoting healthy eating habits and social interaction among students.
       The students from 10th to 12th benefit from the food court during their special classes.</p>',
      'bg_image' => 'canteen1.jpg',
      'carousel' => 
      array (
        0 => 'canteen1.jpg',
        1 => 'canteen2.jpg',
      ),
    ),
    13 => 
    array (
      'name' => 'PlayGround',
      'description_html' => '<p>
      The playground in our school offers a vibrant area for students to engage in physical activities and social interaction.
      </p>',
      'bg_image' => 'playg1.jpg',
      'carousel' => 
      array (
        0 => 'playg1.jpg',
        1 => 'playg2.jpg',
        2 => 'playg3.jpg',
      ),
    ),
    14 => 
    array (
      'name' => 'Mini Auditorium',
      'description_html' => '<p> The mini auditorium  provides a versatile venue for  meetings, seminars,  conferences , orientation class and presentations.</p>',
      'bg_image' => 'miniaud1.jpg',
      'carousel' => 
      array (
        0 => 'miniaud1.jpg',
        1 => 'miniaud2.jpg',
        2 => 'miniaud3.jpg',
      ),
    ),
  ),
  'nav' => 
  array (
    0 => 'Smart Classrooms',
    1 => 'Indoor Auditorium',
    2 => 'Outdoor Auditorium',
    3 => 'Conference Hall',
    4 => 'KG Play Area',
    5 => 'Lab Facilities',
    6 => 'Parking Facility',
    7 => 'Sports Room',
    8 => 'Transport Facility',
    9 => 'Chapel',
    10 => 'E-Library',
    11 => 'Knowledge Center',
    12 => 'Food Court',
    13 => 'PlayGround',
    14 => 'Mini Auditorium',
  ),
);
