<?php
// GENERATED by database/extract-gallery.php (C9) from the static R1c views.
return array (
  'gal-annual' => 
  array (
    'title' => 'Annual Day',
    'years' => 
    array (
      0 => 
      array (
        'label' => '2023',
        'checked' => true,
      ),
      1 => 
      array (
        'label' => '2024',
        'checked' => false,
      ),
    ),
    'photos' => 
    array (
      2023 => 
      array (
        0 => 'annualday1.jpg',
        1 => 'annualday2.jpg',
        2 => 'annualday3.jpg',
        3 => 'annualday4.jpg',
        4 => 'annualday5.jpg',
        5 => 'annualday6.jpg',
        6 => 'annualday7.jpg',
        7 => 'annualday8.jpg',
        8 => 'annualday9.jpg',
        9 => 'annualday10.jpg',
        10 => 'annualday11.jpg',
        11 => 'annualday12.jpg',
        12 => 'annualday13.jpg',
        13 => 'annualday14.jpg',
        14 => 'annualday15.jpg',
        15 => 'annualday16.jpg',
        16 => 'annualday17.jpg',
        17 => 'annualday18.jpg',
        18 => 'annualday19.jpg',
        19 => 'annualday22.jpg',
        20 => 'annualday23.jpg',
      ),
      2024 => 
      array (
        0 => 'ann1.jpg',
        1 => 'annualday19.jpg',
        2 => 'annualday22.jpg',
        3 => 'annualday23.jpg',
        4 => 'ann2.jpg',
        5 => 'ann3.jpg',
        6 => 'ann4.jpg',
        7 => 'ann5.jpg',
      ),
    ),
    'card_image' => 'annualday12.jpg',
    'card_title' => 'Annual Day',
    'card_sub' => '2023 & 2024',
    'hub_pos' => 0,
  ),
  'gal-sports' => 
  array (
    'title' => 'Sports Day',
    'years' => 
    array (
      0 => 
      array (
        'label' => '2023',
        'checked' => true,
      ),
      1 => 
      array (
        'label' => '2022',
        'checked' => false,
      ),
    ),
    'photos' => 
    array (
      2023 => 
      array (
        0 => 'sportsday1.jpg',
        1 => 'sportsday2.jpg',
        2 => 'sportsday3.jpg',
        3 => 'sportsday4.jpg',
        4 => 'sportsday5.jpg',
        5 => 'sportsday6.jpg',
        6 => 'sportsday7.jpg',
        7 => 'sportsday8.jpg',
        8 => 'sportsday9.jpg',
        9 => 'sportsday10.jpg',
        10 => 'sportsday11.jpg',
        11 => 'sportsday12.jpg',
        12 => 'sportsday13.jpg',
        13 => 'sportsday14.jpg',
        14 => 'sportsday15.jpg',
        15 => 'sportsday16.jpg',
        16 => 'sportsday17.jpg',
        17 => 'sportsday18.jpg',
        18 => 'sportsday19.jpg',
        19 => 'sportsday20.jpg',
        20 => 'sportsday21.jpg',
        21 => 'sportsday22.jpg',
        22 => 'sportsday23.jpg',
        23 => 'sportsday24.jpg',
        24 => 'sportsday25.jpg',
        25 => 'sportsday26.jpg',
        26 => 'sportsday27.jpg',
        27 => 'sportsday28.jpg',
        28 => 'sportsday29.jpg',
        29 => 'sportsday30.jpg',
        30 => 'sportsday31.jpg',
        31 => 'sportsday32.jpg',
        32 => 'sportsday33.jpg',
        33 => 'sportsday34.jpg',
        34 => 'sportsday35.jpg',
        35 => 'sportsday36.jpg',
        36 => 'sportsday37.jpg',
        37 => 'sportsday38.jpg',
        38 => 'sportsday39.jpg',
        39 => 'sportsday40.jpg',
        40 => 'sportsday41.jpg',
        41 => 'sportsday42.jpg',
      ),
      2022 => 
      array (
        0 => 'sp1.jpeg',
        1 => 'sp2.jpeg',
        2 => 'sp3.jpeg',
        3 => 'sp4.jpeg',
        4 => 'sp5.jpeg',
        5 => 'sp6.jpeg',
      ),
    ),
    'card_image' => 'sports.jpeg',
    'card_title' => 'Sports Day',
    'card_sub' => '2023 & 2024',
    'hub_pos' => 1,
  ),
  'gal-independence' => 
  array (
    'title' => 'Independence Day',
    'years' => 
    array (
      0 => 
      array (
        'label' => '2023',
        'checked' => true,
      ),
      1 => 
      array (
        'label' => '2022',
        'checked' => false,
      ),
    ),
    'photos' => 
    array (
      2023 => 
      array (
        0 => 'indday1.jpg',
        1 => 'indday2.jpg',
        2 => 'indday3.jpg',
        3 => 'indday4.jpg',
        4 => 'indday5.jpg',
        5 => 'indday6.jpg',
        6 => 'indday7.jpg',
        7 => 'indday8.jpg',
        8 => 'indday9.jpg',
        9 => 'indday10.jpg',
        10 => 'indday11.jpg',
        11 => 'indday12.jpg',
        12 => 'indday13.jpg',
        13 => 'indday14.jpg',
        14 => 'indday15.jpg',
        15 => 'indday16.jpg',
      ),
      2022 => 
      array (
        0 => 'in1.jpeg',
        1 => 'in2.jpeg',
        2 => 'in3.jpeg',
        3 => 'in4.jpeg',
        4 => 'in5.jpeg',
        5 => 'in6.jpeg',
        6 => 'in7.jpeg',
      ),
    ),
    'card_image' => 'indday1.jpg',
    'card_title' => 'Independence Day',
    'card_sub' => '2023 & 2024',
    'hub_pos' => 2,
  ),
  'gal-children' => 
  array (
    'title' => 'Children\'s Day',
    'years' => 
    array (
      0 => 
      array (
        'label' => '2023',
        'checked' => true,
      ),
    ),
    'photos' => 
    array (
      2023 => 
      array (
        0 => 'child1.jpg',
        1 => 'child2.jpg',
        2 => 'childday3.jpg',
        3 => 'childday4.jpg',
        4 => 'childday5.jpg',
        5 => 'childday6.jpeg',
        6 => 'childday7.jpeg',
        7 => 'childday8.jpeg',
        8 => 'childday9.jpeg',
        9 => 'childday10.jpeg',
        10 => 'childday11.jpeg',
        11 => 'childday12.jpeg',
        12 => 'childday13.jpeg',
      ),
    ),
    'card_image' => 'childday1.jpg',
    'card_title' => 'Children\'s Day',
    'card_sub' => '2023',
    'hub_pos' => 3,
  ),
  'gal-teacher' => 
  array (
    'title' => 'Teacher\'s Day',
    'years' => 
    array (
      0 => 
      array (
        'label' => '2023',
        'checked' => true,
      ),
    ),
    'photos' => 
    array (
      2023 => 
      array (
        0 => 'teachday1.jpg',
        1 => 'teachday2.jpg',
        2 => 'teachday3.jpg',
        3 => 'teachday4.jpg',
        4 => 'teachday5.jpg',
        5 => 'teachday6.jpg',
        6 => 'teachday7.jpg',
        7 => 'teachday8.jpg',
        8 => 'teachday9.jpg',
        9 => 'teachday10.jpg',
      ),
    ),
    'card_image' => 'teachday1.jpg',
    'card_title' => 'Teachers Day',
    'card_sub' => '2023',
    'hub_pos' => 4,
  ),
  'gal-expressionz' => 
  array (
    'title' => 'Expressionz Day',
    'years' => 
    array (
      0 => 
      array (
        'label' => '2023',
        'checked' => true,
      ),
    ),
    'photos' => 
    array (
      2023 => 
      array (
        0 => 'expressday1.jpg',
        1 => 'expressday2.jpg',
        2 => 'expressday3.jpg',
        3 => 'expressday4.jpg',
        4 => 'expressday5.jpg',
        5 => 'expressday6.jpg',
        6 => 'expressday7.jpg',
        7 => 'expressday8.jpg',
        8 => 'expressday9.jpg',
        9 => 'expressday10.jpg',
        10 => 'expressday11.jpg',
        11 => 'expressday12.jpg',
        12 => 'expressday13.jpg',
        13 => 'expressday14.jpg',
        14 => 'expressday15.jpg',
        15 => 'expressday16.jpg',
        16 => 'expressday17.jpg',
        17 => 'expressday18.jpg',
        18 => 'expressday19.jpg',
        19 => 'expressday20.jpg',
        20 => 'expressday21.jpg',
        21 => 'expressday22.jpg',
        22 => 'expressday23.jpg',
        23 => 'expressday24.jpg',
        24 => 'expressday25.jpg',
        25 => 'expressday26.jpg',
        26 => 'expressday27.jpg',
        27 => 'expressday28.jpg',
        28 => 'expressday29.jpg',
        29 => 'expressday30.jpg',
        30 => 'expressday31.jpg',
        31 => 'expressday32.jpg',
        32 => 'expressday33.jpg',
        33 => 'expressday34.jpg',
        34 => 'expressday35.jpg',
        35 => 'expressday36.jpg',
        36 => 'expressday37.jpg',
        37 => 'expressday38.jpg',
        38 => 'expressday39.jpg',
        39 => 'expressday40.jpg',
        40 => 'expressday41.jpg',
        41 => 'expressday42.jpg',
        42 => 'expressday43.jpg',
        43 => 'expressday44.jpg',
      ),
    ),
    'card_image' => 'expressday20.jpg',
    'card_title' => 'Expressionz Day',
    'card_sub' => '2023',
    'hub_pos' => 5,
  ),
  'gal-expo' => 
  array (
    'title' => 'Science Expo',
    'years' => 
    array (
      0 => 
      array (
        'label' => '2023',
        'checked' => true,
      ),
      1 => 
      array (
        'label' => '2022',
        'checked' => false,
      ),
    ),
    'photos' => 
    array (
      2023 => 
      array (
        0 => 'expo1.jpg',
        1 => 'expo2.jpg',
        2 => 'expo3.jpg',
        3 => 'expo4.jpg',
        4 => 'expo5.jpg',
        5 => 'expo6.jpg',
        6 => 'expo7.jpg',
        7 => 'expo8.jpg',
        8 => 'expo9.jpg',
        9 => 'expo10.jpg',
        10 => 'expo11.jpg',
        11 => 'expo12.jpg',
        12 => 'expo13.jpg',
        13 => 'expo14.jpg',
        14 => 'expo15.jpg',
        15 => 'expo16.jpg',
        16 => 'expo17.jpg',
        17 => 'expo18.jpg',
        18 => 'expo19.jpg',
        19 => 'expo20.jpg',
        20 => 'expo21.jpg',
        21 => 'expo22.jpg',
        22 => 'expo23.jpg',
        23 => 'expo24.jpg',
        24 => 'expo25.jpg',
        25 => 'expo26.jpg',
        26 => 'expo27.jpg',
        27 => 'expo28.jpg',
        28 => 'expo29.jpg',
        29 => 'expo30.jpg',
        30 => 'expo31.jpg',
        31 => 'expo32.jpg',
        32 => 'expo33.jpg',
        33 => 'expo34.jpg',
      ),
      2022 => 
      array (
        0 => 's1.jpeg',
        1 => 's2.jpeg',
        2 => 's3.jpeg',
        3 => 's4.jpeg',
        4 => 's5.jpeg',
      ),
    ),
    'card_image' => 'expo1.jpg',
    'card_title' => 'Science Expo',
    'card_sub' => '2023 & 2024',
    'hub_pos' => 6,
  ),
  'gal-grad' => 
  array (
    'title' => 'KG Graduation Day',
    'years' => 
    array (
      0 => 
      array (
        'label' => '2023',
        'checked' => true,
      ),
    ),
    'photos' => 
    array (
      2023 => 
      array (
        0 => 'gradday1.jpg',
        1 => 'kggrad3.jpg',
        2 => 'gradday3.jpg',
        3 => 'gradday4.jpg',
        4 => 'gradday5.jpg',
        5 => 'gradday6.jpg',
        6 => 'gradday7.jpg',
        7 => 'gradday8.jpg',
        8 => 'kggrad4.jpg',
        9 => 'gradday10.jpg',
        10 => 'gradday11.jpg',
        11 => 'gradday12.jpg',
        12 => 'gradday13.jpg',
        13 => 'kggrad1.jpg',
        14 => 'kggrad2.jpg',
      ),
    ),
    'card_image' => 'gradday1.jpg',
    'card_title' => 'KG Graduation',
    'card_sub' => '2023',
    'hub_pos' => 7,
  ),
  'gal-alumni' => 
  array (
    'title' => 'Our Alumni',
    'years' => 
    array (
      0 => 
      array (
        'label' => '2023',
        'checked' => true,
      ),
    ),
    'photos' => 
    array (
      2023 => 
      array (
        0 => 'alumni1.png',
        1 => 'alumni2.png',
        2 => 'alumni3.png',
        3 => 'alumni4.png',
        4 => 'alumni5.png',
        5 => 'alumni6.png',
        6 => 'alumni7.png',
        7 => 'alumni8.png',
        8 => 'alumni9.png',
        9 => 'alumni10.png',
      ),
    ),
    'card_image' => 'alumni1.png',
    'card_title' => 'Alumni',
    'card_sub' => '2023',
    'hub_pos' => 8,
  ),
  'gal-spach' => 
  array (
    'title' => 'Sports Achievements',
    'years' => 
    array (
      0 => 
      array (
        'label' => '2023',
        'checked' => true,
      ),
    ),
    'photos' => 
    array (
      2023 => 
      array (
        0 => 'spach1.jpg',
        1 => 'spach2.jpg',
        2 => 'spach3.jpg',
        3 => 'spach4.jpg',
        4 => 'spach5.jpg',
        5 => 'spach6.jpg',
        6 => 'spach7.jpg',
        7 => 'spach8.jpg',
        8 => 'spach9.jpg',
        9 => 'spach10.jpg',
        10 => 'spach11.jpg',
        11 => 'spach12.jpg',
        12 => 'spach13.jpg',
        13 => 'spach14.jpg',
        14 => 'spach15.jpg',
        15 => 'spach16.jpg',
      ),
    ),
    'card_image' => 'spach14.jpg',
    'card_title' => 'Sports Achievements',
    'card_sub' => '2023',
    'hub_pos' => 9,
  ),
);
