<?php
// GENERATED by database/extract-sections.php (C4) from the static R1b views.
// Byte-faithful shipped content — edit via the admin panel, not here.
return array (
  'kg' => 
  array (
    'name' => 'Kinder Garten',
    'events_heading' => 'Events of',
    'intro_heading' => 'Kinder Garten',
    'intro_html' => '<p>At St. Joseph\'s, our preschoolers engage in a vibrant and nurturing environment where learning is a joyful
         experience. Through activities, songs, and weekly assemblies, our little bloomers develop creativity and
          critical thinking. Events like Colors Day, Nature Conservation Day, and Friendship Day, along with art 
          and craft activities, foster their holistic growth. We emphasize 
        the importance of healthy habits and conduct weekly tests to enhance their knowledge and skills.</p>
<p> Learning gives creativity, creativity leads to thinking,thinking gives knowledge and knowledge reinforces you to become a great person in society.
Young children have to seize every moment to learn and develop... Our St.Joseph\'s bloomers are learning through activities and songs... Our school provides a motivating environment for all the children…
Our sweet little kindergartners are conducting Assembly on every Tuesday by the guidance of the teachers…
                    </p>
<p>Colours Day, Expressionz Day, Nature Conservation Day, Independence Day, Friendship Day, Art and Craft Day, Republic Day, Sports Day, Annual Day, 
                        Children\'s Day, Fancy Dress, Christmas Fest, Fruit and Vegetables Day, Music Day are conducted and organised for the improvement of children</p>',
    'timeline_heading' => 'Timeline - 2024',
    'card_title' => 'Kinder Garten(KG)',
    'card_range' => 'LKG-UKG',
    'card_image' => 'kg1.jpg',
    'hero' => 
    array (
      0 => 
      array (
        0 => 'kg4.jpg',
        1 => 'Kinder Garten',
        2 => 'Where students explore how to educate',
      ),
      1 => 
      array (
        0 => 'kg3.jpg',
        1 => 'Kinder Garten',
        2 => 'Where students explore how to educate',
      ),
      2 => 
      array (
        0 => 'kg2.jpg',
        1 => 'Kinder Garten',
        2 => 'Where students explore how to educate',
      ),
    ),
    'carousel' => 
    array (
      0 => 'kg2.jpg',
      1 => 'kg3.jpg',
      2 => 'kg4.jpg',
    ),
    'timeline' => 
    array (
      0 => 
      array (
        0 => 'JUNE',
        1 => '2024 - present',
        2 => '(12-MONDAY)	LKG - WELCOME DAY',
      ),
      1 => 
      array (
        0 => 'JULY',
        1 => '2024 - present',
        2 => '(12-FRIDAY)	KG - GREEN DAY (COLOURING)
(17-WEDNESDAY)	KG - ACTION SONG DAY
(26-FRIDAY)	WORLD NATURE CONSERVATION ( SPEECH COMPETITION)',
      ),
      2 => 
      array (
        0 => 'AUGUST',
        1 => '2024 - present',
        2 => '(7-WEDNESDAY)	KG - SPORTS DAY
(14-WEDNESDAY)	KG - INDEPENDENCE DAY
(26-MONDAY)	KG - FRUITS  DAY',
      ),
      3 => 
      array (
        0 => 'SEPTEMBER',
        1 => '2024 - present',
        2 => '(5-THURSDAY)	TEACHERS DAY
(11-WEDNESDAY)	KG - MAGIC DAY
(13-FRIDAY)	MUSIC DAY / PLAYING INSTRUMENT
(28-SATURDAY)	KG - PTA  JUNCTURE',
      ),
      4 => 
      array (
        0 => 'OCTOBER',
        1 => '2024 - present',
        2 => '(9-WEDNESDAY)	LKG - DOODLES TRIP
(16-WEDNESDAY)	KG - POEM RECITATION / ORIGOMI COMPETITION
(18-FRIDAY)	    MOBILE AWARENESS DAY
(29-TUESDAY)	DIWALI CELEBRATION',
      ),
      5 => 
      array (
        0 => 'NOVEMBER',
        1 => '2024 - present',
        2 => '(6-WEDNESDAY)	KG - MY TALENT
(14-THURSDAY)	CHILDREN\'S DAY
(16-SATURDAY)	KG - FANCY FETE
(22-FRIDAY)	MILLETS DAY FOOD EXPO',
      ),
      6 => 
      array (
        0 => 'DECEMBER',
        1 => '2024 - present',
        2 => '(3-TUESDAY)	PUPPET SHOW
(6-FRIDAY)	KG- CHRISTMAS',
      ),
      7 => 
      array (
        0 => 'JANUARY',
        1 => '2024 - present',
        2 => '(10-FRIDAY)	KG - PONGAL CELEBRATION
(24-FRIDAY)	KG - REPUBLIC DAY ( I MIN SPEECH COMPETITION)',
      ),
      8 => 
      array (
        0 => 'FEBRUARY',
        1 => '2024 - present',
        2 => '(5-WEDNESDAY)	THIRUKKURAL / G.K QUIZ
(7-FRIDAY)	KG - BLUE DAY
(8-SATURDAY)	UKG - EXCURSION
(14-FRIDAY)	KG - FLOWERS DAY
(19-AMAZING) GRAMMAR	AMAZING GRAMMAR
(24-MONDAY)	III MID TERM',
      ),
      9 => 
      array (
        0 => 'MARCH',
        1 => '2024 - present',
        2 => '(5-WEDNESDAY)	OBSERVE & SPEAK COMPETITION
(7-FRIDAY)	KG - DANCE DAY / DANCE COMPETITION
(14-FRIDAY)	KG - CULTURAL DAY',
      ),
    ),
    'events' => 
    array (
      0 => 
      array (
        0 => 'Orange Day',
        1 => '<p>Orange Day is a vibrant celebration of color, creativity, and healthy habits.
                Decorate the classroom with orange streamers, balloons, and cutouts of oranges and carrots.
                </p>',
        2 => 'kg-orange.jpeg',
      ),
      1 => 
      array (
        0 => 'Nature Conservation Day',
        1 => '<p>Raise awareness about conserving natural resources and protecting the environment.
                each about recycling and waste reduction.
                </p>',
        2 => 'kg-natcon.jpg',
      ),
      2 => 
      array (
        0 => 'Fruit and Vegetables Day',
        1 => '<p> Teach children about healthy foods, explore different fruits and vegetables, and understand their importance.
                Promote recycling awareness.
                </p>',
        2 => 'kg-veg.jpeg',
      ),
      3 => 
      array (
        0 => 'Graduation Day',
        1 => '<p> Kindergarten graduation is a special moment that marks the end of a chapter and the beginning of an exciting 
                    educational journey for our little ones. It’s a time filled with pride, joy, and a touch of nostalgia for both
                     parents and their young graduates1.
                     From mastering finger painting to learning the alphabet, these tiny scholars have grown and blossomed.</p>',
        2 => 'kg-grad.jpg',
      ),
    ),
  ),
  'primary' => 
  array (
    'name' => 'Primary School',
    'events_heading' => 'Exams and Events of',
    'intro_heading' => 'Primary School',
    'intro_html' => '<p>The primary section at St. Joseph\'s offers a dynamic learning environment for grades 1 to 5. 
        Students participate in weekly assemblies, celebrate important days, and engage in various activities that promote self-discipline, creativity, and community spirit. 
        We provide worksheets to improve spelling, vocabulary, and math skills. Language education includes French, German, and Spanish, and proficiency tests are conducted 
        to ensure academic standards. Extracurricular activities like yoga, dance, and mental health classes further enrich their educational experience.</p>
<p> Primary school pupils are given access to outings to build life skills for leisure and character development. For students in grades 1to 5 proficiency 
        tests are given to make sure they are meeting academic standards and to prepare them for further 
        study. Classes for late bloomers are held to assist the kids with their academic work and to help 
        them with their learning challenges. Olympiad exams in math and English assist students in developing 
        critical thinking, problem solving, and communication skills that are useful in their academic careers.
         In order to foster fundamental abilities and establish a solid foundation across all courses, worksheets
          in maths, English and Tamil are provided for all classrooms from grade 1 to grade 5.
        </p>
<p>Spoken English classes, Music Classes, Handwriting classes, Examinations, PTA meeting, Extra cultural activities (ECAs), Mental health classes, Counselling session 
            are conducted under the academic curriculum itself. </p>',
    'timeline_heading' => 'Timeline - 2024',
    'card_title' => 'Primary School',
    'card_range' => '1st - 5th',
    'card_image' => 'primary4.jpg',
    'hero' => 
    array (
      0 => 
      array (
        0 => 'primary4.jpg',
        1 => 'Primary School',
        2 => 'Where students explore how to educate',
      ),
      1 => 
      array (
        0 => 'primary2.jpg',
        1 => 'Primary School',
        2 => 'Where students explore how to educate',
      ),
      2 => 
      array (
        0 => 'primary1.jpg',
        1 => 'Primary School',
        2 => 'Where students explore how to educate',
      ),
    ),
    'carousel' => 
    array (
      0 => 'primary2.jpg',
      1 => 'primary3.jpg',
      2 => 'primary4.jpg',
    ),
    'timeline' => 
    array (
      0 => 
      array (
        0 => 'JUNE',
        1 => '2024 - present',
        2 => '1.(21)  International Music Day
2.Competition:  Drawing – Fruits',
      ),
      1 => 
      array (
        0 => 'JULY',
        1 => '2024 - present',
        2 => '1.(30)  International Day of Friendship
2.Competition: Handwriting [English]
3.[EXPRESSIONZ]',
      ),
      2 => 
      array (
        0 => 'AUGUST',
        1 => '2024 - present',
        2 => '1. Sports Day
2. Independence Day
3. Competition: Handwriting[TAMIL]',
      ),
      3 => 
      array (
        0 => 'SEPTEMBER',
        1 => '2024 - present',
        2 => '1.Teacher’s Day
2.I Terminal Exam',
      ),
      4 => 
      array (
        0 => 'OCTOBER',
        1 => '2024 - present',
        2 => '1.11th - International Day of Girl Child
2.Competition: Pick the words.
3.PTA Meeting  [ I – V STD]',
      ),
      5 => 
      array (
        0 => 'NOVEMBER',
        1 => '2024 - present',
        2 => '1.Annual Day
2.Children’s Day
3.Bharat English Proficiency Test
4.Competition : Reading [English]',
      ),
      6 => 
      array (
        0 => 'DECEMBER',
        1 => '2024 - present',
        2 => '1.Christmas Day
2.II Terminal Exam',
      ),
      7 => 
      array (
        0 => 'JANUARY',
        1 => '2024 - present',
        2 => '1.(10) World  Hindi Day
2.MATHS Olympiad [Level I, II & III]
3.Pongal Celebration
4.Republic Day
5.Competition: Reading [TAMIL]',
      ),
      8 => 
      array (
        0 => 'FEBRUARY',
        1 => '2024 - present',
        2 => '1.(21) International Mother Language Day
2.MATHS Olympiad [ Level - IV]
3.SPELLATHON Level [ I, II, III ]
4.Competition: Dictation Words[Tamil and English]
5.Field Trip',
      ),
      9 => 
      array (
        0 => 'MARCH',
        1 => '2024 - present',
        2 => '1.St. Joseph’s Feast Day
2.Competition: Quiz',
      ),
    ),
    'events' => 
    array (
      0 => 
      array (
        0 => 'The Expressionz Day',
        1 => '<p>Expression Day at school was a vibrant event where students showcased their talents in art, music, dance, and drama. 
                    Each participant had the opportunity to express their creativity through various performances and exhibits. 
                    The day fostered a sense of community and celebrated the diverse skills of students.</p>',
        2 => 'primary-expression.jpg',
      ),
      1 => 
      array (
        0 => 'The Music Classes',
        1 => '<p>Music classes in school focus on teaching students the fundamentals of music theory, instrumental practice, and vocal training. 
                    Students engage in learning different genres, understanding rhythms, and performing both individually and in groups. 
                    These classes help in developing students\' musical abilities and fostering a love for music.</p>',
        2 => 'vocaca2.jpg',
      ),
    ),
  ),
  'highschl' => 
  array (
    'name' => 'High School',
    'events_heading' => 'Exams and Events of',
    'intro_heading' => 'High School',
    'intro_html' => '<p>St. Joseph\'s High School encourages holistic development through various club activities and innovative programs. Our subject-specific clubs, such as the Excel English Academy 
        and Math Magicians Academy, create a unique environment for knowledge sharing and idea propagation. We offer worksheets, language education, and proficiency tests to enhance
         academic skills. Events like Science Expos, Math Olympiads,
         and field trips foster practical learning. Celebrations of important days and a focus on soft skills and mental health ensure well-rounded growth for our students.</p>
<p>Our school conducts club activities  in all the subjects <br>
    1.Valanarilakkiamandram (TAMIL)<br>
    2.Excel Engish Academy(ENGLISH)<br>
    3.Math magicians Academy(MATHS)<br>
    4.Master minds Academy (SCIENCE)<br>
    5.Patriotic panthers Academy(SOCIAL SCINCE) <br>
These clubs create a unique environment where knowledge is shared ideas are welcomed and optimistic values are propagated leaving a little room forcompetition. <br>
Exposure visits are made to learn from the experience by direct interactions our students are taken to different places to have direct experiences

                    </p>',
    'timeline_heading' => 'Timeline - 2024',
    'card_title' => 'High School',
    'card_range' => '6th - 10th',
    'card_image' => 'high1.jpg',
    'hero' => 
    array (
      0 => 
      array (
        0 => 'high4.jpg',
        1 => 'High School',
        2 => 'Where students explore how to educate',
      ),
      1 => 
      array (
        0 => 'high2.jpg',
        1 => 'High School',
        2 => 'Where students explore how to educate',
      ),
      2 => 
      array (
        0 => 'high1.jpg',
        1 => 'High School',
        2 => 'Where students explore how to educate',
      ),
    ),
    'carousel' => 
    array (
      0 => 'high2.jpg',
      1 => 'high3.jpg',
      2 => 'high4.jpg',
    ),
    'timeline' => 
    array (
      0 => 
      array (
        0 => 'JUNE',
        1 => '2024 - present',
        2 => '1.Inaugural function for all Academics
2.Work sheet -1 (Tam, Eng, Mat)
3.Proficiency test (Tam, Eng, Mat)
4.Science expo preparation
5.Field trip (Art gallery, Isha Yoga)',
      ),
      1 => 
      array (
        0 => 'JULY',
        1 => '2024 - present',
        2 => '1.Exprezions ‘24
2.Kamarajar day (Tam dep)
3.Science expo
4.Drawing competition (SST)
5.Work sheet -2 (Tam, Eng, Mat)
6.Orientation class
7.Tamil reading practice',
      ),
      2 => 
      array (
        0 => 'AUGUST',
        1 => '2024 - present',
        2 => '1.Work sheet -3 (Tam, Eng, Mat)
2.Independence day
3.English essay writing (Humanitarian day)
4.Sports day',
      ),
      3 => 
      array (
        0 => 'SEPTEMBER',
        1 => '2024 - present',
        2 => '1.Worksheet -4 (Tam, Eng, Mat)
2.Teachers day celebration
3.Ozone day (Seminar)
4.English reading
5.World cleanliness day (sep 15th ) -Classroom cleaning
6.SST Quiz competition',
      ),
      4 => 
      array (
        0 => 'OCTOBER',
        1 => '2024 - present',
        2 => '1.Work sheet -5 (Tam, Eng, Mat)
2.Mental Health day (combined with Star school)
3.Girl child day (seminar)
4.Proficiency test
5.PTA meeting',
      ),
      5 => 
      array (
        0 => 'NOVEMBER',
        1 => '2024 - present',
        2 => '1.Children’s day competition (committee)
2.Work Sheet -6 (Tam, Eng, Mat)
3.Annual day',
      ),
      6 => 
      array (
        0 => 'DECEMBER',
        1 => '2024 - present',
        2 => '1.Work sheet -7 (Tam, Eng, Mat)
2.Bharathiar Birthday - Dec 11th (Tam dep)
3.Ramanujan Birthday - Dec 22nd (Mat dep)
4.Christmas day Celebration',
      ),
      7 => 
      array (
        0 => 'JANUARY',
        1 => '2024 - present',
        2 => '1.Work sheet -8 (Tam, Eng, Mat)
2.Maths Olympiad (Education day )
3.National Science day (Sci dep)
4.Republic day
5.PTA meeting (open day )
6.Pongal celebration (Tam dep)
7.SST Expo',
      ),
      8 => 
      array (
        0 => 'FEBRUARY',
        1 => '2024 - present',
        2 => '1.Work sheet -9 (Tam, Eng, Mat)
2.Proficiency test
3.World Peace day -Feb 23rd (MSC teachers)
4.Valedictory function',
      ),
      9 => 
      array (
        0 => 'MARCH',
        1 => '2024 - present',
        2 => '1.Work sheet -10 (Tam, Eng, Mat)
2.Women’s day - Mar 8th  (Eng dep)
3.water day 22nd (Sci and Sst dep)
4.Annual exam
                                            5.PTA meeting',
      ),
    ),
    'events' => 
    array (
      0 => 
      array (
        0 => 'The Unit Tests',
        1 => '<p>Regular unit tests in high school play a crucial role in the academic 
                    development of students. These assessments are designed to evaluate 
                    students’ understanding of the material covered in each unit, ensuring
                     that they grasp key concepts before moving on to more advanced topics. </p>',
        2 => 'high3.jpg',
      ),
      1 => 
      array (
        0 => 'The Expressionz Day',
        1 => '<p>Expression Day at school was a vibrant event where students showcased their talents in art, music, dance, and drama. 
                    Each participant had the opportunity to express their creativity through various performances and exhibits. 
                    The day fostered a sense of community and celebrated the diverse skills of students.</p>',
        2 => 'high-expression.jpg',
      ),
    ),
  ),
  'highsec' => 
  array (
    'name' => 'Higher Secondary',
    'events_heading' => 'Exams and Events of',
    'intro_heading' => 'Higher Secondary',
    'intro_html' => '<p>The Higher Secondary section at St. Joseph\'s prepares students for future academic and professional success. We offer foundation courses for science students, 
        communication skill classes, and career guidance. Our rigorous academic schedule includes daily unit tests, monthly tests, and practical exams, aiming for centum results.
         Special attention is given to slow learners through counseling and extra coaching. Students participate in district-level competitions, various celebrations, 
         and orientation programs.
         We emphasize discipline, attendance, and overall excellence, with regular feedback and support from dedicated teachers and staff.</p>
<p> For students in grades X, XI, and XII, the school offers orientation programs, field trips, and foundation courses for science students.
         Communication skills classes, motivational sessions by the Principal, and career guidance from reputed faculty are provided. Students 
         participate in events like Expression Day, Sports Day, Annual Day, Teachers\' Day, and Pongal. Leadership elections are held, feedback 
         is collected, and counseling sessions support slow learners. Merit certificates, fee concessions, and awards for academic achievements 
         are given. Regular assessments, extra coaching, and dress code adherence are enforced. Participation in district-level competitions and 
         a mental health curriculum are encouraged. Teachers visit students\' homes for additional support. Celebrations for 100% results include 
         holidays and a visit from the Bishop. PTA meetings discuss student performance. Snacks are available for purchase, and canteen issues are 
         managed by the Principal. Special tests and extended school hours help academic improvement. Students are encouraged to take online exams,
          and external teachers handle half-yearly paper corrections. Academy candidates strengthen science education. During board exams, transport
           is provided, and special prayers are held.
         Post-exam feedback and result discussions involve all teachers. Students struggling with Tamil are advised to take French.
                    </p>',
    'timeline_heading' => 'Timeline - 2024',
    'card_title' => 'Higher Secondary',
    'card_range' => '11th - 12th',
    'card_image' => 'highsec1.jpg',
    'hero' => 
    array (
      0 => 
      array (
        0 => 'highsec4.jpg',
        1 => 'Higher Secondary',
        2 => 'Where students explore how to educate',
      ),
      1 => 
      array (
        0 => 'highsec3.jpg',
        1 => 'Higher Secondary',
        2 => 'Where students explore how to educate',
      ),
      2 => 
      array (
        0 => 'highsec2.jpg',
        1 => 'Higher Secondary',
        2 => 'Where students explore how to educate',
      ),
    ),
    'carousel' => 
    array (
      0 => 'highsec2.jpg',
      1 => 'highsec3.jpg',
      2 => 'highsec4.jpg',
    ),
    'timeline' => 
    array (
      0 => 
      array (
        0 => 'MAY',
        1 => '2024 - present',
        2 => '1.Dr. Shilpa Terrance –Seminar
2.Foundation Course
3.Carrier Program – Prabha Mam',
      ),
      1 => 
      array (
        0 => 'JUNE',
        1 => '2024 - present',
        2 => '1.Election
2.Investiture Ceremony
3.Unit Test
4.Field Trip
5.PTA Meeting',
      ),
      2 => 
      array (
        0 => 'JULY',
        1 => '2024 - present',
        2 => '1.Monthly Test
2.Exprezions’24  Kamarajar Birday
3.Science Expo
4.Strengthening Course
5.Unit Test',
      ),
      3 => 
      array (
        0 => 'AUGUST',
        1 => '2024 - present',
        2 => '1.Unit Test
2.Independence Day
3.Quiz competition.
4.Record Completion & Submission (Aug 31)',
      ),
      4 => 
      array (
        0 => 'SEPTEMBER',
        1 => '2024 - present',
        2 => '1.I Terminal Exam
2.Practicals
3.Completion of Portion
4.Teachers’s day Celebration',
      ),
      5 => 
      array (
        0 => 'OCTOBER',
        1 => '2024 - present',
        2 => '1.Hard topic Revision
2.Tests
3.Diwali Celebration',
      ),
      6 => 
      array (
        0 => 'NOVEMBER',
        1 => '2024 - present',
        2 => '1.I Week –Volume I (Revision & Tests)
2.II Week –Volume I (Revision & Tests)
3.III Week –Volume II(Revision & Tests)
4.IV Week – Volume II (Revision & Tests)
5.Children’s Day Celebration
6.Annual Day',
      ),
      7 => 
      array (
        0 => 'DECEMBER',
        1 => '2024 - present',
        2 => '1.Christmas Day –Function
2.Model Practical
3.II Terminal Exam',
      ),
      8 => 
      array (
        0 => 'JANUARY',
        1 => '2024 - present',
        2 => '1.I Revision / II Revision
2.Pongal Celebration',
      ),
      9 => 
      array (
        0 => 'FEBRUARY',
        1 => '2024 - present',
        2 => '1.Public Practical Exam
2.III Revision  Exam',
      ),
      10 => 
      array (
        0 => 'MARCH',
        1 => '2024 - present',
        2 => '1.Board Exam',
      ),
    ),
    'events' => 
    array (
      0 => 
      array (
        0 => 'The Unit Tests',
        1 => '<p>The school conducts weekly unit tests to regularly assess students\' understanding and retention of the material covered in their courses. 
                    These tests help identify areas where students may need additional support and ensure continuous academic progress.
                     Regular testing also prepares students for larger exams by building their confidence and test-taking skills.</p>',
        2 => 'highsec-unit.jpg',
      ),
      1 => 
      array (
        0 => 'The Alumni Awards',
        1 => '<p>The school honors its distinguished alumni through an annual awards ceremony. 
                    These awards recognize alumni for their outstanding achievements in various fields and contributions to society. 
                    The event serves to inspire current students by showcasing the success of former students and fostering a sense of pride and aspiration within the school community.</p>',
        2 => 'highsec-alumni.png',
      ),
    ),
  ),
);
