<?php
// GENERATED by database/extract-sports.php (C6) from the static R1a view.
// Byte-faithful shipped content — edit via the admin panel, not here.
return array (
  'hero' => 
  array (
    0 => 
    array (
      0 => 'spoathlet.jpg',
      1 => 'Our Sports',
      2 => 'About our Sports',
    ),
    1 => 
    array (
      0 => 'spofencing.jpg',
      1 => 'Our Sports',
      2 => 'About our Sports',
    ),
    2 => 
    array (
      0 => 'spohandb.jpg',
      1 => 'Our Sports',
      2 => 'About our Sports',
    ),
  ),
  'sports' => 
  array (
    0 => 
    array (
      'name' => 'Athletics',
      'training_time' => 'Training Time 3.30-5.00p.m',
      'details_html' => 'Sports athletes deserve appreciation for their dedication, hard work, and the inspiration they provide. They often become role models, demonstrating values like perseverance, teamwork, and resilience. Beyond their performance, many athletes engage in charitable activities, use their platforms for social causes, and contribute positively to their communities. Whether through remarkable achievements or personal integrity, their impact extends far beyond the sports arena.',
      'image' => 'spoathlet.jpg',
    ),
    1 => 
    array (
      'name' => 'Badminton',
      'training_time' => 'Training Time 3.30-5.00p.m',
      'details_html' => 'Badminton is a fast-paced racket sport played either in singles or doubles. It requires agility, precision, and strategic thinking. In Our  School Training is given students everyday soon after the academic classes. (3.30- 5.00 pm) Our team achieved Zonal winners and District participated.
    <br><br>
                Our school students are zonal level winners and participated in District level.',
      'image' => 'spobadminton.jpg',
    ),
    2 => 
    array (
      'name' => 'Hand Ball',
      'training_time' => 'Training Time 3.30-5.00p.m',
      'details_html' => 'Congratulations to the  our handball champions! Your dedication, teamwork, and relentless effort have paid off, showcasing incredible skill and sportsmanship. You\'ve set a high standard and inspired many with your outstanding performance. Category wise Students take their practising secessions.
<br>Under 14 BOYS AND GIRLS.  Zonal winners <br>
Under 17 BOYS Zonal winners <br>
Under 19 GIRLS.  Zonal runner.<br>
Under 14 GIRLS\'  ACHIEVEMENT : Revenue District IV PLACE.<br>',
      'image' => 'spohandb.jpg',
    ),
    3 => 
    array (
      'name' => 'Fencing',
      'training_time' => 'Training Time(Wednesday)3.30-5.00p.m',
      'details_html' => 'Fencing game is introduced in our school. <br>
                Fencing is a sport that involves two competitors fighting with swords while trying to score points by making contact with their opponent in specific target areas. There are three main types of weapons used in fencing: foil, epee, and sabre, each with its own rules and techniques. Fencing is known for its fast-paced action, strategic depth, and emphasis on agility and precision.
It is scheduled on wednesday evening.',
      'image' => 'spofencing.jpg',
    ),
    4 => 
    array (
      'name' => 'Skating',
      'training_time' => 'Training Time(MON-TUE-WED) 6.00-7.00p.m',
      'details_html' => 'Skating game is introduced newly in our school with professional training.',
      'image' => 'sposkating.jpg',
    ),
    5 => 
    array (
      'name' => 'Table Tennis',
      'training_time' => 'Training Time 6.30-8.00p.m',
      'details_html' => 'Our school students are zonal winners. <br> District level winners. <br>And participated in state level for district SGFI selection.',
      'image' => 'spotablet.jpg',
    ),
    6 => 
    array (
      'name' => 'Tennikoit',
      'training_time' => 'Training Time 3.30-5.30p.m',
      'details_html' => 'Our school students are zonal winners and participated in District level.',
      'image' => 'spotennikoit.jpg',
    ),
    7 => 
    array (
      'name' => 'Volley Ball',
      'training_time' => 'Training Time 3.30-5.30p.m',
      'details_html' => 'Participated in Zonal level.',
      'image' => 'spovolley.jpg',
    ),
    8 => 
    array (
      'name' => 'Throw Ball',
      'training_time' => 'Training Time 3.30-5.30p.m',
      'details_html' => 'Participated in Zonal level.',
      'image' => 'spothrow.jpg',
    ),
  ),
  'suffixes' => 
  array (
    0 => '',
    1 => '2',
    2 => '3',
  ),
);
